// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClassOnlineAction.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ClassOnlineAction.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace METRO {
namespace CRO {
namespace MESSAGES {

namespace {

const ::google::protobuf::Descriptor* ClassOnlineAction_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClassOnlineAction_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ClassOnlineAction_ActionType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ClassOnlineAction_2eproto() {
  protobuf_AddDesc_ClassOnlineAction_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ClassOnlineAction.proto");
  GOOGLE_CHECK(file != NULL);
  ClassOnlineAction_descriptor_ = file->message_type(0);
  static const int ClassOnlineAction_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassOnlineAction, targetusername_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassOnlineAction, classid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassOnlineAction, actiontype_),
  };
  ClassOnlineAction_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClassOnlineAction_descriptor_,
      ClassOnlineAction::default_instance_,
      ClassOnlineAction_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassOnlineAction, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassOnlineAction, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClassOnlineAction));
  ClassOnlineAction_ActionType_descriptor_ = ClassOnlineAction_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ClassOnlineAction_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClassOnlineAction_descriptor_, &ClassOnlineAction::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ClassOnlineAction_2eproto() {
  delete ClassOnlineAction::default_instance_;
  delete ClassOnlineAction_reflection_;
}

void protobuf_AddDesc_ClassOnlineAction_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::METRO::CRO::MESSAGES::protobuf_AddDesc_IpcMessage_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027ClassOnlineAction.proto\022\022METRO.CRO.MES"
    "SAGES\032\020IpcMessage.proto\"\337\002\n\021ClassOnlineA"
    "ction\022\026\n\016targetusername\030\001 \001(\t\022\017\n\007classid"
    "\030\002 \001(\005\022D\n\nactiontype\030\003 \001(\01620.METRO.CRO.M"
    "ESSAGES.ClassOnlineAction.ActionType\"\201\001\n"
    "\nActionType\022\016\n\nOPEN_CLASS\020\001\022\017\n\013CLOSE_CLA"
    "SS\020\002\022\021\n\rREQUEST_JOINT\020\003\022\020\n\014ACCEPT_JOINT\020"
    "\004\022\026\n\022REQUEST_DRAW_BOARD\020\005\022\025\n\021ACCEPT_DRAW"
    "_BOARD\020\0062W\n\007message\022\036.METRO.CRO.MESSAGES"
    ".IpcMessage\030\257\002 \001(\0132%.METRO.CRO.MESSAGES."
    "ClassOnlineAction", 417);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ClassOnlineAction.proto", &protobuf_RegisterTypes);
  ClassOnlineAction::default_instance_ = new ClassOnlineAction();
  ClassOnlineAction::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::METRO::CRO::MESSAGES::IpcMessage::default_instance(),
    303, 11, false, false,
    &::METRO::CRO::MESSAGES::ClassOnlineAction::default_instance());
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ClassOnlineAction_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ClassOnlineAction_2eproto {
  StaticDescriptorInitializer_ClassOnlineAction_2eproto() {
    protobuf_AddDesc_ClassOnlineAction_2eproto();
  }
} static_descriptor_initializer_ClassOnlineAction_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ClassOnlineAction_ActionType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClassOnlineAction_ActionType_descriptor_;
}
bool ClassOnlineAction_ActionType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ClassOnlineAction_ActionType ClassOnlineAction::OPEN_CLASS;
const ClassOnlineAction_ActionType ClassOnlineAction::CLOSE_CLASS;
const ClassOnlineAction_ActionType ClassOnlineAction::REQUEST_JOINT;
const ClassOnlineAction_ActionType ClassOnlineAction::ACCEPT_JOINT;
const ClassOnlineAction_ActionType ClassOnlineAction::REQUEST_DRAW_BOARD;
const ClassOnlineAction_ActionType ClassOnlineAction::ACCEPT_DRAW_BOARD;
const ClassOnlineAction_ActionType ClassOnlineAction::ActionType_MIN;
const ClassOnlineAction_ActionType ClassOnlineAction::ActionType_MAX;
const int ClassOnlineAction::ActionType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ClassOnlineAction::kTargetusernameFieldNumber;
const int ClassOnlineAction::kClassidFieldNumber;
const int ClassOnlineAction::kActiontypeFieldNumber;
#endif  // !_MSC_VER

#ifndef _MSC_VER
const int ClassOnlineAction::kMessageFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::METRO::CRO::MESSAGES::IpcMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::METRO::CRO::MESSAGES::ClassOnlineAction >, 11, false >
  ClassOnlineAction::message(kMessageFieldNumber, ::METRO::CRO::MESSAGES::ClassOnlineAction::default_instance());
ClassOnlineAction::ClassOnlineAction()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:METRO.CRO.MESSAGES.ClassOnlineAction)
}

void ClassOnlineAction::InitAsDefaultInstance() {
}

ClassOnlineAction::ClassOnlineAction(const ClassOnlineAction& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:METRO.CRO.MESSAGES.ClassOnlineAction)
}

void ClassOnlineAction::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  targetusername_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  classid_ = 0;
  actiontype_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClassOnlineAction::~ClassOnlineAction() {
  // @@protoc_insertion_point(destructor:METRO.CRO.MESSAGES.ClassOnlineAction)
  SharedDtor();
}

void ClassOnlineAction::SharedDtor() {
  if (targetusername_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete targetusername_;
  }
  if (this != default_instance_) {
  }
}

void ClassOnlineAction::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClassOnlineAction::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClassOnlineAction_descriptor_;
}

const ClassOnlineAction& ClassOnlineAction::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClassOnlineAction_2eproto();
  return *default_instance_;
}

ClassOnlineAction* ClassOnlineAction::default_instance_ = NULL;

ClassOnlineAction* ClassOnlineAction::New() const {
  return new ClassOnlineAction;
}

void ClassOnlineAction::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_targetusername()) {
      if (targetusername_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        targetusername_->clear();
      }
    }
    classid_ = 0;
    actiontype_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClassOnlineAction::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:METRO.CRO.MESSAGES.ClassOnlineAction)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string targetusername = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_targetusername()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->targetusername().data(), this->targetusername().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "targetusername");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_classid;
        break;
      }

      // optional int32 classid = 2;
      case 2: {
        if (tag == 16) {
         parse_classid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &classid_)));
          set_has_classid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_actiontype;
        break;
      }

      // optional .METRO.CRO.MESSAGES.ClassOnlineAction.ActionType actiontype = 3;
      case 3: {
        if (tag == 24) {
         parse_actiontype:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::METRO::CRO::MESSAGES::ClassOnlineAction_ActionType_IsValid(value)) {
            set_actiontype(static_cast< ::METRO::CRO::MESSAGES::ClassOnlineAction_ActionType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:METRO.CRO.MESSAGES.ClassOnlineAction)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:METRO.CRO.MESSAGES.ClassOnlineAction)
  return false;
#undef DO_
}

void ClassOnlineAction::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:METRO.CRO.MESSAGES.ClassOnlineAction)
  // optional string targetusername = 1;
  if (has_targetusername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->targetusername().data(), this->targetusername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "targetusername");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->targetusername(), output);
  }

  // optional int32 classid = 2;
  if (has_classid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->classid(), output);
  }

  // optional .METRO.CRO.MESSAGES.ClassOnlineAction.ActionType actiontype = 3;
  if (has_actiontype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->actiontype(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:METRO.CRO.MESSAGES.ClassOnlineAction)
}

::google::protobuf::uint8* ClassOnlineAction::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:METRO.CRO.MESSAGES.ClassOnlineAction)
  // optional string targetusername = 1;
  if (has_targetusername()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->targetusername().data(), this->targetusername().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "targetusername");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->targetusername(), target);
  }

  // optional int32 classid = 2;
  if (has_classid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->classid(), target);
  }

  // optional .METRO.CRO.MESSAGES.ClassOnlineAction.ActionType actiontype = 3;
  if (has_actiontype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->actiontype(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:METRO.CRO.MESSAGES.ClassOnlineAction)
  return target;
}

int ClassOnlineAction::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string targetusername = 1;
    if (has_targetusername()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->targetusername());
    }

    // optional int32 classid = 2;
    if (has_classid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->classid());
    }

    // optional .METRO.CRO.MESSAGES.ClassOnlineAction.ActionType actiontype = 3;
    if (has_actiontype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->actiontype());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClassOnlineAction::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClassOnlineAction* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClassOnlineAction*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClassOnlineAction::MergeFrom(const ClassOnlineAction& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_targetusername()) {
      set_targetusername(from.targetusername());
    }
    if (from.has_classid()) {
      set_classid(from.classid());
    }
    if (from.has_actiontype()) {
      set_actiontype(from.actiontype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClassOnlineAction::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClassOnlineAction::CopyFrom(const ClassOnlineAction& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassOnlineAction::IsInitialized() const {

  return true;
}

void ClassOnlineAction::Swap(ClassOnlineAction* other) {
  if (other != this) {
    std::swap(targetusername_, other->targetusername_);
    std::swap(classid_, other->classid_);
    std::swap(actiontype_, other->actiontype_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClassOnlineAction::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClassOnlineAction_descriptor_;
  metadata.reflection = ClassOnlineAction_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MESSAGES
}  // namespace CRO
}  // namespace METRO

// @@protoc_insertion_point(global_scope)
