// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClassroomInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ClassroomInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace METRO {
namespace CRO {
namespace MESSAGES {

namespace {

const ::google::protobuf::Descriptor* ClassroomInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClassroomInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ClassroomInfo_2eproto() {
  protobuf_AddDesc_ClassroomInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ClassroomInfo.proto");
  GOOGLE_CHECK(file != NULL);
  ClassroomInfo_descriptor_ = file->message_type(0);
  static const int ClassroomInfo_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, u_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, cate_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, teacher_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, description_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, imgurl_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, time_open_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, time_close_),
  };
  ClassroomInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClassroomInfo_descriptor_,
      ClassroomInfo::default_instance_,
      ClassroomInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassroomInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClassroomInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ClassroomInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClassroomInfo_descriptor_, &ClassroomInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ClassroomInfo_2eproto() {
  delete ClassroomInfo::default_instance_;
  delete ClassroomInfo_reflection_;
}

void protobuf_AddDesc_ClassroomInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::METRO::CRO::MESSAGES::protobuf_AddDesc_IpcMessage_2eproto();
  ::METRO::CRO::MESSAGES::protobuf_AddDesc_User_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023ClassroomInfo.proto\022\022METRO.CRO.MESSAGE"
    "S\032\020IpcMessage.proto\032\nUser.proto\"\210\002\n\rClas"
    "sroomInfo\022\014\n\004u_id\030\001 \002(\t\022\017\n\007cate_id\030\002 \002(\t"
    "\022\014\n\004name\030\003 \002(\t\022)\n\007teacher\030\004 \002(\0132\030.METRO."
    "CRO.MESSAGES.User\022\023\n\013description\030\005 \001(\t\022\016"
    "\n\006imgurl\030\006 \001(\t\022\021\n\ttime_open\030\007 \001(\t\022\022\n\ntim"
    "e_close\030\010 \001(\t2S\n\007message\022\036.METRO.CRO.MES"
    "SAGES.IpcMessage\030\313\001 \001(\0132!.METRO.CRO.MESS"
    "AGES.ClassroomInfo", 338);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ClassroomInfo.proto", &protobuf_RegisterTypes);
  ClassroomInfo::default_instance_ = new ClassroomInfo();
  ClassroomInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::METRO::CRO::MESSAGES::IpcMessage::default_instance(),
    203, 11, false, false,
    &::METRO::CRO::MESSAGES::ClassroomInfo::default_instance());
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ClassroomInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ClassroomInfo_2eproto {
  StaticDescriptorInitializer_ClassroomInfo_2eproto() {
    protobuf_AddDesc_ClassroomInfo_2eproto();
  }
} static_descriptor_initializer_ClassroomInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ClassroomInfo::kUIdFieldNumber;
const int ClassroomInfo::kCateIdFieldNumber;
const int ClassroomInfo::kNameFieldNumber;
const int ClassroomInfo::kTeacherFieldNumber;
const int ClassroomInfo::kDescriptionFieldNumber;
const int ClassroomInfo::kImgurlFieldNumber;
const int ClassroomInfo::kTimeOpenFieldNumber;
const int ClassroomInfo::kTimeCloseFieldNumber;
#endif  // !_MSC_VER

#ifndef _MSC_VER
const int ClassroomInfo::kMessageFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::METRO::CRO::MESSAGES::IpcMessage,
    ::google::protobuf::internal::MessageTypeTraits< ::METRO::CRO::MESSAGES::ClassroomInfo >, 11, false >
  ClassroomInfo::message(kMessageFieldNumber, ::METRO::CRO::MESSAGES::ClassroomInfo::default_instance());
ClassroomInfo::ClassroomInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:METRO.CRO.MESSAGES.ClassroomInfo)
}

void ClassroomInfo::InitAsDefaultInstance() {
  teacher_ = const_cast< ::METRO::CRO::MESSAGES::User*>(&::METRO::CRO::MESSAGES::User::default_instance());
}

ClassroomInfo::ClassroomInfo(const ClassroomInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:METRO.CRO.MESSAGES.ClassroomInfo)
}

void ClassroomInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  u_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cate_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  teacher_ = NULL;
  description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  imgurl_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_open_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_close_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClassroomInfo::~ClassroomInfo() {
  // @@protoc_insertion_point(destructor:METRO.CRO.MESSAGES.ClassroomInfo)
  SharedDtor();
}

void ClassroomInfo::SharedDtor() {
  if (u_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete u_id_;
  }
  if (cate_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cate_id_;
  }
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (imgurl_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete imgurl_;
  }
  if (time_open_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete time_open_;
  }
  if (time_close_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete time_close_;
  }
  if (this != default_instance_) {
    delete teacher_;
  }
}

void ClassroomInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClassroomInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClassroomInfo_descriptor_;
}

const ClassroomInfo& ClassroomInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClassroomInfo_2eproto();
  return *default_instance_;
}

ClassroomInfo* ClassroomInfo::default_instance_ = NULL;

ClassroomInfo* ClassroomInfo::New() const {
  return new ClassroomInfo;
}

void ClassroomInfo::Clear() {
  if (_has_bits_[0 / 32] & 255) {
    if (has_u_id()) {
      if (u_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        u_id_->clear();
      }
    }
    if (has_cate_id()) {
      if (cate_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        cate_id_->clear();
      }
    }
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    if (has_teacher()) {
      if (teacher_ != NULL) teacher_->::METRO::CRO::MESSAGES::User::Clear();
    }
    if (has_description()) {
      if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        description_->clear();
      }
    }
    if (has_imgurl()) {
      if (imgurl_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        imgurl_->clear();
      }
    }
    if (has_time_open()) {
      if (time_open_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        time_open_->clear();
      }
    }
    if (has_time_close()) {
      if (time_close_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        time_close_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClassroomInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:METRO.CRO.MESSAGES.ClassroomInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string u_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_u_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->u_id().data(), this->u_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "u_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_cate_id;
        break;
      }

      // required string cate_id = 2;
      case 2: {
        if (tag == 18) {
         parse_cate_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cate_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cate_id().data(), this->cate_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cate_id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_name;
        break;
      }

      // required string name = 3;
      case 3: {
        if (tag == 26) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_teacher;
        break;
      }

      // required .METRO.CRO.MESSAGES.User teacher = 4;
      case 4: {
        if (tag == 34) {
         parse_teacher:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_teacher()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_description;
        break;
      }

      // optional string description = 5;
      case 5: {
        if (tag == 42) {
         parse_description:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->description().data(), this->description().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "description");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_imgurl;
        break;
      }

      // optional string imgurl = 6;
      case 6: {
        if (tag == 50) {
         parse_imgurl:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_imgurl()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->imgurl().data(), this->imgurl().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "imgurl");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_time_open;
        break;
      }

      // optional string time_open = 7;
      case 7: {
        if (tag == 58) {
         parse_time_open:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_time_open()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->time_open().data(), this->time_open().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "time_open");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_time_close;
        break;
      }

      // optional string time_close = 8;
      case 8: {
        if (tag == 66) {
         parse_time_close:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_time_close()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->time_close().data(), this->time_close().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "time_close");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:METRO.CRO.MESSAGES.ClassroomInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:METRO.CRO.MESSAGES.ClassroomInfo)
  return false;
#undef DO_
}

void ClassroomInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:METRO.CRO.MESSAGES.ClassroomInfo)
  // required string u_id = 1;
  if (has_u_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->u_id().data(), this->u_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "u_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->u_id(), output);
  }

  // required string cate_id = 2;
  if (has_cate_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cate_id().data(), this->cate_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cate_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->cate_id(), output);
  }

  // required string name = 3;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // required .METRO.CRO.MESSAGES.User teacher = 4;
  if (has_teacher()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->teacher(), output);
  }

  // optional string description = 5;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->description(), output);
  }

  // optional string imgurl = 6;
  if (has_imgurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->imgurl().data(), this->imgurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "imgurl");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->imgurl(), output);
  }

  // optional string time_open = 7;
  if (has_time_open()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time_open().data(), this->time_open().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "time_open");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->time_open(), output);
  }

  // optional string time_close = 8;
  if (has_time_close()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time_close().data(), this->time_close().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "time_close");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->time_close(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:METRO.CRO.MESSAGES.ClassroomInfo)
}

::google::protobuf::uint8* ClassroomInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:METRO.CRO.MESSAGES.ClassroomInfo)
  // required string u_id = 1;
  if (has_u_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->u_id().data(), this->u_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "u_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->u_id(), target);
  }

  // required string cate_id = 2;
  if (has_cate_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cate_id().data(), this->cate_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cate_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->cate_id(), target);
  }

  // required string name = 3;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // required .METRO.CRO.MESSAGES.User teacher = 4;
  if (has_teacher()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->teacher(), target);
  }

  // optional string description = 5;
  if (has_description()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->description().data(), this->description().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->description(), target);
  }

  // optional string imgurl = 6;
  if (has_imgurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->imgurl().data(), this->imgurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "imgurl");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->imgurl(), target);
  }

  // optional string time_open = 7;
  if (has_time_open()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time_open().data(), this->time_open().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "time_open");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->time_open(), target);
  }

  // optional string time_close = 8;
  if (has_time_close()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time_close().data(), this->time_close().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "time_close");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->time_close(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:METRO.CRO.MESSAGES.ClassroomInfo)
  return target;
}

int ClassroomInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string u_id = 1;
    if (has_u_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->u_id());
    }

    // required string cate_id = 2;
    if (has_cate_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cate_id());
    }

    // required string name = 3;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required .METRO.CRO.MESSAGES.User teacher = 4;
    if (has_teacher()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->teacher());
    }

    // optional string description = 5;
    if (has_description()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->description());
    }

    // optional string imgurl = 6;
    if (has_imgurl()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->imgurl());
    }

    // optional string time_open = 7;
    if (has_time_open()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->time_open());
    }

    // optional string time_close = 8;
    if (has_time_close()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->time_close());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClassroomInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClassroomInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClassroomInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClassroomInfo::MergeFrom(const ClassroomInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_u_id()) {
      set_u_id(from.u_id());
    }
    if (from.has_cate_id()) {
      set_cate_id(from.cate_id());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_teacher()) {
      mutable_teacher()->::METRO::CRO::MESSAGES::User::MergeFrom(from.teacher());
    }
    if (from.has_description()) {
      set_description(from.description());
    }
    if (from.has_imgurl()) {
      set_imgurl(from.imgurl());
    }
    if (from.has_time_open()) {
      set_time_open(from.time_open());
    }
    if (from.has_time_close()) {
      set_time_close(from.time_close());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClassroomInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClassroomInfo::CopyFrom(const ClassroomInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassroomInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  if (has_teacher()) {
    if (!this->teacher().IsInitialized()) return false;
  }
  return true;
}

void ClassroomInfo::Swap(ClassroomInfo* other) {
  if (other != this) {
    std::swap(u_id_, other->u_id_);
    std::swap(cate_id_, other->cate_id_);
    std::swap(name_, other->name_);
    std::swap(teacher_, other->teacher_);
    std::swap(description_, other->description_);
    std::swap(imgurl_, other->imgurl_);
    std::swap(time_open_, other->time_open_);
    std::swap(time_close_, other->time_close_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClassroomInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClassroomInfo_descriptor_;
  metadata.reflection = ClassroomInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MESSAGES
}  // namespace CRO
}  // namespace METRO

// @@protoc_insertion_point(global_scope)
