// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Enums.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace METRO {
namespace CRO {
namespace MESSAGES {

namespace {

const ::google::protobuf::Descriptor* Enums_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Enums_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Enums_ResponseLoginEnums_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Enums_2eproto() {
  protobuf_AddDesc_Enums_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Enums.proto");
  GOOGLE_CHECK(file != NULL);
  Enums_descriptor_ = file->message_type(0);
  static const int Enums_offsets_[1] = {
  };
  Enums_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Enums_descriptor_,
      Enums::default_instance_,
      Enums_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Enums, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Enums, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Enums));
  Enums_ResponseLoginEnums_descriptor_ = Enums_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Enums_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Enums_descriptor_, &Enums::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Enums_2eproto() {
  delete Enums::default_instance_;
  delete Enums_reflection_;
}

void protobuf_AddDesc_Enums_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Enums.proto\022\022METRO.CRO.MESSAGES\"@\n\005Enu"
    "ms\"7\n\022ResponseLoginEnums\022\013\n\007SUCCESS\020\000\022\024\n"
    "\020FAILD_WRONG_PASS\020\001", 99);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Enums.proto", &protobuf_RegisterTypes);
  Enums::default_instance_ = new Enums();
  Enums::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Enums_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Enums_2eproto {
  StaticDescriptorInitializer_Enums_2eproto() {
    protobuf_AddDesc_Enums_2eproto();
  }
} static_descriptor_initializer_Enums_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* Enums_ResponseLoginEnums_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Enums_ResponseLoginEnums_descriptor_;
}
bool Enums_ResponseLoginEnums_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Enums_ResponseLoginEnums Enums::SUCCESS;
const Enums_ResponseLoginEnums Enums::FAILD_WRONG_PASS;
const Enums_ResponseLoginEnums Enums::ResponseLoginEnums_MIN;
const Enums_ResponseLoginEnums Enums::ResponseLoginEnums_MAX;
const int Enums::ResponseLoginEnums_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
#endif  // !_MSC_VER

Enums::Enums()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:METRO.CRO.MESSAGES.Enums)
}

void Enums::InitAsDefaultInstance() {
}

Enums::Enums(const Enums& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:METRO.CRO.MESSAGES.Enums)
}

void Enums::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Enums::~Enums() {
  // @@protoc_insertion_point(destructor:METRO.CRO.MESSAGES.Enums)
  SharedDtor();
}

void Enums::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Enums::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Enums::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Enums_descriptor_;
}

const Enums& Enums::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Enums_2eproto();
  return *default_instance_;
}

Enums* Enums::default_instance_ = NULL;

Enums* Enums::New() const {
  return new Enums;
}

void Enums::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Enums::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:METRO.CRO.MESSAGES.Enums)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:METRO.CRO.MESSAGES.Enums)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:METRO.CRO.MESSAGES.Enums)
  return false;
#undef DO_
}

void Enums::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:METRO.CRO.MESSAGES.Enums)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:METRO.CRO.MESSAGES.Enums)
}

::google::protobuf::uint8* Enums::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:METRO.CRO.MESSAGES.Enums)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:METRO.CRO.MESSAGES.Enums)
  return target;
}

int Enums::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Enums::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Enums* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Enums*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Enums::MergeFrom(const Enums& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Enums::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Enums::CopyFrom(const Enums& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Enums::IsInitialized() const {

  return true;
}

void Enums::Swap(Enums* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Enums::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Enums_descriptor_;
  metadata.reflection = Enums_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MESSAGES
}  // namespace CRO
}  // namespace METRO

// @@protoc_insertion_point(global_scope)
