// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "BoardErase.pb.h"
// @@protoc_insertion_point(imports)

@implementation BoardEraseRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [BoardEraseRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface BoardErase ()
@property SInt32 lineid;
@end

@implementation BoardErase

- (BOOL) hasLineid {
  return !!hasLineid_;
}
- (void) setHasLineid:(BOOL) _value_ {
  hasLineid_ = !!_value_;
}
@synthesize lineid;
- (instancetype) init {
  if ((self = [super init])) {
    self.lineid = 0;
  }
  return self;
}
static BoardErase* defaultBoardEraseInstance = nil;
+ (void) initialize {
  if (self == [BoardErase class]) {
    defaultBoardEraseInstance = [[BoardErase alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultBoardEraseInstance;
}
- (instancetype) defaultInstance {
  return defaultBoardEraseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasLineid) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasLineid) {
    [output writeInt32:1 value:self.lineid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasLineid) {
    size_ += computeInt32Size(1, self.lineid);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (BoardErase*) parseFromData:(NSData*) data {
  return (BoardErase*)[[[BoardErase builder] mergeFromData:data] build];
}
+ (BoardErase*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoardErase*)[[[BoardErase builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (BoardErase*) parseFromInputStream:(NSInputStream*) input {
  return (BoardErase*)[[[BoardErase builder] mergeFromInputStream:input] build];
}
+ (BoardErase*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoardErase*)[[[BoardErase builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BoardErase*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (BoardErase*)[[[BoardErase builder] mergeFromCodedInputStream:input] build];
}
+ (BoardErase*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (BoardErase*)[[[BoardErase builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (BoardEraseBuilder*) builder {
  return [[BoardEraseBuilder alloc] init];
}
+ (BoardEraseBuilder*) builderWithPrototype:(BoardErase*) prototype {
  return [[BoardErase builder] mergeFrom:prototype];
}
- (BoardEraseBuilder*) builder {
  return [BoardErase builder];
}
- (BoardEraseBuilder*) toBuilder {
  return [BoardErase builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasLineid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"lineid", [NSNumber numberWithInteger:self.lineid]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasLineid) {
    [dictionary setObject: [NSNumber numberWithInteger:self.lineid] forKey: @"lineid"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[BoardErase class]]) {
    return NO;
  }
  BoardErase *otherMessage = other;
  return
      self.hasLineid == otherMessage.hasLineid &&
      (!self.hasLineid || self.lineid == otherMessage.lineid) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasLineid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.lineid] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface BoardEraseBuilder()
@property (strong) BoardErase* resultBoardErase;
@end

@implementation BoardEraseBuilder
@synthesize resultBoardErase;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultBoardErase = [[BoardErase alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultBoardErase;
}
- (BoardEraseBuilder*) clear {
  self.resultBoardErase = [[BoardErase alloc] init];
  return self;
}
- (BoardEraseBuilder*) clone {
  return [BoardErase builderWithPrototype:resultBoardErase];
}
- (BoardErase*) defaultInstance {
  return [BoardErase defaultInstance];
}
- (BoardErase*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (BoardErase*) buildPartial {
  BoardErase* returnMe = resultBoardErase;
  self.resultBoardErase = nil;
  return returnMe;
}
- (BoardEraseBuilder*) mergeFrom:(BoardErase*) other {
  if (other == [BoardErase defaultInstance]) {
    return self;
  }
  if (other.hasLineid) {
    [self setLineid:other.lineid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (BoardEraseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (BoardEraseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setLineid:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasLineid {
  return resultBoardErase.hasLineid;
}
- (SInt32) lineid {
  return resultBoardErase.lineid;
}
- (BoardEraseBuilder*) setLineid:(SInt32) value {
  resultBoardErase.hasLineid = YES;
  resultBoardErase.lineid = value;
  return self;
}
- (BoardEraseBuilder*) clearLineid {
  resultBoardErase.hasLineid = NO;
  resultBoardErase.lineid = 0;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
