#ifndef IPCMESSAGETYPE_H
#define IPCMESSAGETYPE_H

#define USER_BASE   100
#define USER_MSG    (USER_BASE + 1)
#define TEACHER_MSG (USER_BASE + 2)
#define REQUEST_LOGIN_MSG (USER_BASE + 3)
#define RESPONSE_LOGIN_MSG (USER_BASE + 4)
#define USER_INIT_MSG (USER_BASE + 5)

#define CLASS_BASE 200
#define CATEGORY_MSG (CLASS_BASE + 1)
#define CALSSROOM_MSG (CLASS_BASE + 2)

#endif // IPCMESSAGETYPE_H
