// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IpcMessage.pb.h"
// @@protoc_insertion_point(imports)

@class IpcMessage;
@class IpcMessageBuilder;
@class RequestLogin;
@class RequestLoginBuilder;



@interface RequestLoginRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define RequestLogin_username @"username"
#define RequestLogin_password @"password"
@interface RequestLogin : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUsername_:1;
  BOOL hasPassword_:1;
  NSString* username;
  NSString* password;
}
- (BOOL) hasUsername;
- (BOOL) hasPassword;
@property (readonly, strong) NSString* username;
@property (readonly, strong) NSString* password;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) message;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RequestLoginBuilder*) builder;
+ (RequestLoginBuilder*) builder;
+ (RequestLoginBuilder*) builderWithPrototype:(RequestLogin*) prototype;
- (RequestLoginBuilder*) toBuilder;

+ (RequestLogin*) parseFromData:(NSData*) data;
+ (RequestLogin*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RequestLogin*) parseFromInputStream:(NSInputStream*) input;
+ (RequestLogin*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RequestLogin*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RequestLogin*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RequestLoginBuilder : PBGeneratedMessageBuilder {
@private
  RequestLogin* resultRequestLogin;
}

- (RequestLogin*) defaultInstance;

- (RequestLoginBuilder*) clear;
- (RequestLoginBuilder*) clone;

- (RequestLogin*) build;
- (RequestLogin*) buildPartial;

- (RequestLoginBuilder*) mergeFrom:(RequestLogin*) other;
- (RequestLoginBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RequestLoginBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUsername;
- (NSString*) username;
- (RequestLoginBuilder*) setUsername:(NSString*) value;
- (RequestLoginBuilder*) clearUsername;

- (BOOL) hasPassword;
- (NSString*) password;
- (RequestLoginBuilder*) setPassword:(NSString*) value;
- (RequestLoginBuilder*) clearPassword;
@end


// @@protoc_insertion_point(global_scope)
