// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "User.pb.h"
#import "ClassCategory.pb.h"
#import "ClassroomInfo.pb.h"
// @@protoc_insertion_point(imports)

@class ClassCategory;
@class ClassCategoryBuilder;
@class ClassroomInfo;
@class ClassroomInfoBuilder;
@class User;
@class UserBuilder;
@class UserInit;
@class UserInitBuilder;



@interface UserInitRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define UserInit_userinfo @"userinfo"
#define UserInit_categories @"categories"
#define UserInit_ownerclass @"ownerclass"
@interface UserInit : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserinfo_:1;
  User* userinfo;
  NSMutableArray * categoriesArray;
  NSMutableArray * ownerclassArray;
}
- (BOOL) hasUserinfo;
@property (readonly, strong) User* userinfo;
@property (readonly, strong) NSArray * categories;
@property (readonly, strong) NSArray * ownerclass;
- (ClassCategory*)categoriesAtIndex:(NSUInteger)index;
- (ClassroomInfo*)ownerclassAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserInitBuilder*) builder;
+ (UserInitBuilder*) builder;
+ (UserInitBuilder*) builderWithPrototype:(UserInit*) prototype;
- (UserInitBuilder*) toBuilder;

+ (UserInit*) parseFromData:(NSData*) data;
+ (UserInit*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInit*) parseFromInputStream:(NSInputStream*) input;
+ (UserInit*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInit*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserInit*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserInitBuilder : PBGeneratedMessageBuilder {
@private
  UserInit* resultUserInit;
}

- (UserInit*) defaultInstance;

- (UserInitBuilder*) clear;
- (UserInitBuilder*) clone;

- (UserInit*) build;
- (UserInit*) buildPartial;

- (UserInitBuilder*) mergeFrom:(UserInit*) other;
- (UserInitBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserInitBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserinfo;
- (User*) userinfo;
- (UserInitBuilder*) setUserinfo:(User*) value;
- (UserInitBuilder*) setUserinfoBuilder:(UserBuilder*) builderForValue;
- (UserInitBuilder*) mergeUserinfo:(User*) value;
- (UserInitBuilder*) clearUserinfo;

- (NSMutableArray *)categories;
- (ClassCategory*)categoriesAtIndex:(NSUInteger)index;
- (UserInitBuilder *)addCategories:(ClassCategory*)value;
- (UserInitBuilder *)setCategoriesArray:(NSArray *)array;
- (UserInitBuilder *)clearCategories;

- (NSMutableArray *)ownerclass;
- (ClassroomInfo*)ownerclassAtIndex:(NSUInteger)index;
- (UserInitBuilder *)addOwnerclass:(ClassroomInfo*)value;
- (UserInitBuilder *)setOwnerclassArray:(NSArray *)array;
- (UserInitBuilder *)clearOwnerclass;
@end


// @@protoc_insertion_point(global_scope)
