// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "IpcMessage.pb.h"
// @@protoc_insertion_point(imports)

@class IpcMessage;
@class IpcMessageBuilder;
@class User;
@class UserBuilder;



@interface UserRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define User_username @"username"
#define User_email @"email"
#define User_fullname @"fullname"
#define User_yearofborn @"yearofborn"
#define User_imgurl @"imgurl"
@interface User : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasYearofborn_:1;
  BOOL hasUsername_:1;
  BOOL hasEmail_:1;
  BOOL hasFullname_:1;
  BOOL hasImgurl_:1;
  SInt32 yearofborn;
  NSString* username;
  NSString* email;
  NSString* fullname;
  NSString* imgurl;
}
- (BOOL) hasUsername;
- (BOOL) hasEmail;
- (BOOL) hasFullname;
- (BOOL) hasYearofborn;
- (BOOL) hasImgurl;
@property (readonly, strong) NSString* username;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* fullname;
@property (readonly) SInt32 yearofborn;
@property (readonly, strong) NSString* imgurl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

+ (id<PBExtensionField>) message;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBuilder*) builder;
+ (UserBuilder*) builder;
+ (UserBuilder*) builderWithPrototype:(User*) prototype;
- (UserBuilder*) toBuilder;

+ (User*) parseFromData:(NSData*) data;
+ (User*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (User*) parseFromInputStream:(NSInputStream*) input;
+ (User*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (User*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (User*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBuilder : PBGeneratedMessageBuilder {
@private
  User* resultUser;
}

- (User*) defaultInstance;

- (UserBuilder*) clear;
- (UserBuilder*) clone;

- (User*) build;
- (User*) buildPartial;

- (UserBuilder*) mergeFrom:(User*) other;
- (UserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUsername;
- (NSString*) username;
- (UserBuilder*) setUsername:(NSString*) value;
- (UserBuilder*) clearUsername;

- (BOOL) hasEmail;
- (NSString*) email;
- (UserBuilder*) setEmail:(NSString*) value;
- (UserBuilder*) clearEmail;

- (BOOL) hasFullname;
- (NSString*) fullname;
- (UserBuilder*) setFullname:(NSString*) value;
- (UserBuilder*) clearFullname;

- (BOOL) hasYearofborn;
- (SInt32) yearofborn;
- (UserBuilder*) setYearofborn:(SInt32) value;
- (UserBuilder*) clearYearofborn;

- (BOOL) hasImgurl;
- (NSString*) imgurl;
- (UserBuilder*) setImgurl:(NSString*) value;
- (UserBuilder*) clearImgurl;
@end


// @@protoc_insertion_point(global_scope)
